# Generated by Django 5.2.8 on 2025-12-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalcomment',
            name='professional',
            field=models.CharField(max_length=150),
        ),
    ]
