# Generated by Django 5.2.8 on 2025-12-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_panel', '0002_alter_professionalcomment_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalcomment',
            name='is_from_professional',
            field=models.BooleanField(default=True),
        ),
    ]
